### ISSUE TITLE
Field Schema Name is always lowercase

### ISSUE THREAD

**Issue by foosfam** [tcorcor1/FieldCreator.TyCorcoran#1]
A great tool but unusable as the Schema Names always reformat to lowercase.

If you could fix this I know a lot of people that would be excited...!!!

**Comment by tcorcor1** [comment]
Thanks for the feedback. Let me do some testing and get back with you.

**Comment by foosfam** [comment]
Thanks, Ty for the quick reply...!
Looking forward to what you find.
🍺😃👍

**Comment by foosfam** [comment]
> Thanks for the feedback. Let me do some testing and get back with you.

Morning Ty, is there a quick fix for this?  If not, we will have to move ahead manually - and it will be awful - but I figured I'd check in with you to see if was something straight forward to release.

**Comment by foosfam** [comment]
Ty, I found it...!  In AttrBase.cs at line 22 you are doing the following:

`public string AttrSchemaName => Regex.Replace(_attribute.FieldSchemaName.ToLower(), _regexSanitizedSchemaName, string.Empty);`

Looks like a copy and paste error from line 19.

Could you remove the `.ToLower()` from that line...?

Could you do a quick release tonight?  Thanks so much!  🍺😃👍

**Comment by tcorcor1** [comment]
Yup, I am aware of that. I plan to work on it tonight and will let you know.

**Comment by foosfam** [comment]
Very nice!  Thanks Ty!  How long does it take to show up on an XrmToolBox update?  (Or you can send me the new DLL and I'll just drop it in the XTB plugin folder and test for you)

**Comment by tcorcor1** [comment]
It's live now. 

XTB lets you force updates so you will see a new version there next time you check (v4.2021.4.7)

**Comment by foosfam** [comment]
> It's live now.
> 
> XTB lets you force updates so you will see a new version there next time you check (v4.2021.4.7)

**LET'S GOOOO!!!!**  👍👍👍  
Jumping on to test now... I'll let you know how it goes.  Thanks Ty!

**Comment by foosfam** [comment]
@tcorcor1 - Works like a champ and rated 5 stars!!!
https://www.xrmtoolbox.com/plugins/plugininfo/?id=b768ab03-3cc5-ea11-bf21-2818786f65dd

**Thanks so much Ty.  Legendary support and fix.**  🛡️🏆🗡️

**Comment by tcorcor1** [comment]
Thanks man, much appreciated! I am glad to help

**Comment by foosfam** [comment]
You are most welcome brother!!!
My colleague will be dropping another ⭐⭐⭐⭐⭐ review tomorrow as well.
Note: You literally saved him at least 2 if not 3 days of migrating fields. 😄 Thanks Again!

**Comment by tcorcor1** [comment]
That's what I love to hear!
