### ISSUE TITLE
The language code 1033 is not a valid language for this organization

### ISSUE THREAD

**Issue by kkoTuTo** [tcorcor1/FieldCreator.TyCorcoran#3]
The language code I am using is 2052

**Comment by kkoTuTo** [comment]
Can you help me solve this problem

**Comment by tcorcor1** [comment]
Hi Frank,
Sorry about this, I see the issue. Let me work on this and test a new build over the next couple days. Will have an update for you soon.

**Comment by FrankZhu1020** [comment]
Thank you, I'm new to dynamics development. I am currently going to modify your source code, I would like to know how to recompile your source code to solve the problem I need to use now

---Original---
From: "Ty ***@***.***&gt;
Date: Sat, Feb 19, 2022 10:53 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tcorcor1/FieldCreator.TyCorcoran] The language code 1033 is nota valid language for this organization (Issue #3)




 
Hi Frank,
 Sorry about this, I see the issue. Let me work on this and test a new build. Will have an update for you soon.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kkoTuTo** [comment]
thanks&nbsp; ☺️☺️☺️



---Original---
From: "Ty ***@***.***&gt;
Date: Sat, Feb 19, 2022 10:53 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tcorcor1/FieldCreator.TyCorcoran] The language code 1033 is nota valid language for this organization (Issue #3)




 
Hi Frank,
 Sorry about this, I see the issue. Let me work on this and test a new build. Will have an update for you soon.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tcorcor1** [comment]
You can clone this repo and build. Make sure to build in release mode as ILMerge needs to merge the CsvHelper assembly. Once you have your DLL you can add it to the XTB plugins folder on your local and use it. 

I am sure you have this already but below is some great documentation on debugging XTB tools:
https://github.com/MscrmTools/XrmToolBox/wiki/Debug-your-plugins-during-development

**Comment by FrankZhu1020** [comment]
Hi Tcorcot1
thank you! But currently I have some problems，how can i create nuget package？

**Comment by tcorcor1** [comment]
Hi Frank,
I released an update I hope will fix this problem. Can you please update the plugin (v5.2022.2.21) and let me know?

**Comment by kkoTuTo** [comment]
Hi Tcorcot1，
Good morning!
Thank you very much, I have received this update now and it works fine after testing! Thank you again!

**Comment by kkoTuTo** [comment]
The problem you helped me with saved me a lot of time, you are awesome！
