### ISSUE TITLE
Question about lookup fields

### ISSUE THREAD

**Issue by kkoTuTo** [tcorcor1/FieldCreator.TyCorcoran#4]
Hi Tcorcor，
Sorry to bother you again!
I'm having trouble creating a lookup field。
I have filled in the schema name but he prompted me "The schema name of an entity relationship must be provided" 
Thanks man, much appreciated!@tcorcor1 
[FieldCreator_Template.xlsx](https://github.com/tcorcor1/FieldCreator.TyCorcoran/files/8121506/FieldCreator_Template.xlsx)
![屏幕截图 2022-02-23 103642](https://user-images.githubusercontent.com/99472773/155253141-c052eead-8cde-4d0a-b3a1-9658d3019097.png)
![屏幕截图 2022-02-23 103739](https://user-images.githubusercontent.com/99472773/155253143-23ca1c4c-a118-4ef6-9815-0ee41ccfeed3.png)

**Comment by tcorcor1** [comment]
Hi @FrankZhu1020 ,
You will have to fill out column S and T in the import template:
![image](https://user-images.githubusercontent.com/45568306/155554471-824ba489-6fce-4360-bb66-ffb4d8100dbf.png)

**Comment by kkoTuTo** [comment]
You are wonderful! Thank Tcorcor!
But may I give you some advice?
Whether it is possible to create the corresponding entity according to a sheet table, and can automatically create the entity

**Comment by tcorcor1** [comment]
Hi @FrankZhu1020,
Thanks for the feedback! 

I think for now I would like to keep the "singleness of purpose" for this plugin. I will definitely keep that in mind for a future enhancement.
