### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by Bleauhaus** [tcorcor1/FieldCreator.TyCorcoran#6]
Trying to use Field Creator, and wondering if there is a tool to download my existing field data to use as a template/crib sheet? The tool comes with sample data but I am looking to see a sample of what is in my solution [Noob in over my head]

**Comment by tcorcor1** [comment]
I use an XrmToolbox tool called Metadata Document Generator when I need to get that info, it's great. It exports most attribute properties you would find in the import template but not all. It should be helpful getting started. 

I'll tag this as an enhancement idea and look into it next time I get around to doing a release for this plugin.

**Comment by Bleauhaus** [comment]
That would be Boss in a single tool...I wound up going with Attribute
Explorer, which was just a dump of the whole environmendt which then had to
sort through and delete 33000 rows...

MEtaDocGenerator is a much better choice tjanks for the info
